version: '3.3'

services:
  app:
    build:
      dockerfile: Dockerfile
    working_dir: /app
    env_file: .env
    command: node index.js
    ports:
      - '${BOT_PORT}:${BOT_PORT}'
      - '5000:5000'
    volumes:
      - './app:/app:delegated'
      - '~/.bash_history:/root/.bash_history:delegated'
      - '.bashrc:/root/.bashrc:delegated'
      - '/var/run/docker.sock:/var/run/docker.sock:delegated'
      - '/var/tmp:/var/tmp:delegated'
      - '/tmp:/tmp:delegated'
